version: '3.8'

services:
  eric7:
    build: .
    container_name: eric7_ide
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
      - MODEL_URL=${MODEL_URL}
      - MODEL_DIR=${MODEL_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/workspace
    working_dir: /workspace
    command: python3 -m eric7_ide
    network_mode: host
    stdin_open: true
    tty: true