version: '3.8'

services:
  eric7:
    build: .
    container_name: eric7_ide
    env_file:
      - .env
    environment:
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_SOFTWARE: "1"
      MESA_LOADER_DRIVER_OVERRIDE: "softpipe"
      QTWEBENGINE_CHROMIUM_FLAGS: "--no-sandbox"
      QT_X11_NO_MITSHM: "1"
      MODEL_URL: ${MODEL_URL}
      MODEL_DIR: ${MODEL_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/workspace
    working_dir: /workspace
    command: python3 eric7_ide.py
    network_mode: host
    stdin_open: true
    tty: true